apiVersion: v1
kind: Secret
metadata:
    name: go-kubernetes-apps-secrets
    namespace: go-kubernetes-apps
type: Opaque
data:
    go_kubernetes_db_user: cm9vdA==
    go_kubernetes_db_password: cGFzc3cwcmQ=
    